### ISSUE TITLE
添加到yolov11

### ISSUE THREAD

**Issue by xj996** [yang-0201/MAF-YOLO#3]
请问一下现在这个MAF是基于yolov6开发的，有迁移到yolov10或者更高版本的可能吗，应该怎么修改

**Comment by yang-0201** [comment]
目前这边已经基于yolov10开发了MAFv2，会在不久后开源，可以关注下。
v10，v11的改法是一样的，因为都采用了yaml文件来构建网络结构 ，你需要做的仅仅是将MAF中的每个模块注册到v10，v11当中，并更改v10，v11中的yaml文件就 可以正常运行了。

**Comment by xj996** [comment]
期待后续更新！

**Comment by yang-0201** [comment]
已上传，可以看下新版本，https://github.com/yang-0201/MAF-YOLOv2
